[package]
name = "traefik-powerdns-bridge"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.7.0"
anyhow = "1.0.86"
reqwest = { version = "0.12.4", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
